In [41]:
import numpy as np

# 1D Array Oluşturma ve Erişim
arr1d = np.array([0, 2, 4, 6])
print("1D Array:")
print(arr1d)
print("First element:", arr1d[0])

# 2D Array Oluşturma ve Erişim
arr2d = np.array([[0, 1, 2], [3, 4, 5]])
print("\n2D Array:")
print(arr2d)
print("First row:", arr2d[0])
print("First element of first row:", arr2d[0][0])

# np.zeros ile Diziler Oluşturma
np4 = np.zeros(6)  # 6 veri
print("\nZeros Array (np.zeros(6)):")
print(np4)

# np.ones ile Birlerden Oluşan Diziler Oluşturma
ones_array = np.ones((2, 3))  # 2 satır, 3 sütun
print("\nOnes Array (np.ones((2, 3))):")
print(ones_array)

# np.arange ile Dizi Oluşturma
np2 = np.arange(5)
np3 = np.arange(0, 7, 2)
print("\nRange:")
print("Range(5):", np2)
print("Step by step arange (0 to 7 with step 2):", np3)

# np.zeros ile Çok Boyutlu Diziler Oluşturma
np5 = np.zeros((2, 5))
print("\nMultidimensional Zeros:")
print(np5)

# np.full ile Belirli Bir Değerle Dizi Oluşturma
np6 = np.full((3), 5)
np7 = np.full((2, 4), 3)
print("\nFull Array:")
print("Full (3):", np6)
print("Multidimensional Full (2x4):", np7)


1D Array:
[0 2 4 6]
First element: 0

2D Array:
[[0 1 2]
 [3 4 5]]
First row: [0 1 2]
First element of first row: 0

Zeros Array (np.zeros(6)):
[0. 0. 0. 0. 0. 0.]

Ones Array (np.ones((2, 3))):
[[1. 1. 1.]
 [1. 1. 1.]]

Range:
Range(5): [0 1 2 3 4]
Step by step arange (0 to 7 with step 2): [0 2 4 6]

Multidimensional Zeros:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Full Array:
Full (3): [5 5 5]
Multidimensional Full (2x4): [[3 3 3 3]
 [3 3 3 3]]


In [40]:
# Array İşlemleri
print("\nArray Operations")
print()

# Dizileri Sıralama
arr1d.sort()
print("Sorted 1D array:", arr1d)

# Diziyi Eksen Bazında Sıralama
arr2d.sort(axis=0)
print("\nSorted 2D array along axis 0:")
print(arr2d)


Array Operations

Sorted 1D array: [0 2 4 6]

Sorted 2D array along axis 0:
[[0 1 2]
 [3 4 5]]


In [24]:
#DATA


print("Dimension of arr1d:", arr1d.ndim)  # 1 boyutlu dizi
print("Dimension of arr2d:", arr2d.ndim)  # 2 boyutlu dizi


print("Length of array a:", len(arr1d))


print("\nShape of arr1d:", arr1d.shape)  # (5,) - 5 elemanlı tek boyutlu dizi
print("Shape of arr2d:", arr2d.shape)  # (3, 3) - 3x3'lük iki boyutlu dizi

print("\nSize of arr1d:", arr1d.size)  # 5
print("Size of arr2d:", arr2d.size)  # 9

# Dizinin Veri Tipi
print("\nData type of arr1d:", arr1d.dtype)  # int64
print("Data type of arr2d:", arr2d.dtype)  # int64
print("Name of data type of array arr1d:", arr1d.dtype.name)


# Dizinin Elemanlarına Erişme
print("\nFirst element of arr1d:", arr1d[0])  # İlk eleman
print("Last element of arr2d:", arr2d[-1, -1])  # Son eleman

# Dizinin Veri Tipini Değiştirme
b_int = arr1d.astype(float)
print("Array b converted to float type:\n", b_int)

Dimension of arr1d: 1
Dimension of arr2d: 2
Length of array a: 4

Shape of arr1d: (4,)
Shape of arr2d: (3, 3)

Size of arr1d: 4
Size of arr2d: 9

Data type of arr1d: int32
Data type of arr2d: int32
Name of data type of array arr1d: int32

First element of arr1d: 0
Last element of arr2d: 9
Array b converted to float type:
 [0. 2. 4. 6.]


In [32]:
import numpy as np

#slicing numpy arrays
np1=np.array([1,2,3,4,5,6,7,8,9])

#return 2,3,4,5
print(np1[1:5])

#return from something till the end of the array?
print(np1[3:])

#return negative slices( tersten başlıyor)
print(np1[-3:-1])

#steps
print(np1[1:5])
print(np1[1:8:3])
print(np1[::4])

[2 3 4 5]
[4 5 6 7 8 9]
[7 8]
[2 3 4 5]
[2 5 8]
[1 5 9]


In [16]:
import numpy as np

np1=np.array([9,2,0,1])
print(np1)
#square route
print('\nsquare root:\n',np.sqrt(np1))

# Üs Alma
power_array = np.power(np1, 3)
print("\nCube of arr1:\n", power_array)


#absolute value
print('\nAbsolute values\n',np.absolute(np1))

#exponents
print('Exponents:', np.exp(np1))

#min max
print('max num:',np.max(np1))
print('min num:',np.min(np1))
mean_value = np.mean(np1)
print("\nMean value of arr1:", mean_value)

# Standart Sapma
std_deviation = np.std(np1)
print("Standard deviation of arr1:", std_deviation)

# Median
median_value = np.median(np1)
print("\nMedian value of arr1:", median_value)


[9 2 0 1]

square root:
 [3.         1.41421356 0.         1.        ]

Cube of arr1:
 [729   8   0   1]

Absolute values
 [9 2 0 1]
Exponents: [8.10308393e+03 7.38905610e+00 1.00000000e+00 2.71828183e+00]
max num: 9
min num: 0

Mean value of arr1: 3.0
Standard deviation of arr1: 3.5355339059327378

Median value of arr1: 1.5


In [14]:
# Broadcasting

# Örnek 1: Farklı boyutlardaki dizilerin toplanması
arr3 = np.array([1, 2, 3])
arr4 = np.array([[4], [5], [6]])
broadcast_sum = arr3 + arr4
print("Broadcasting sum of arr3 and arr4:\n", broadcast_sum)

# Örnek 2: Dizilerin yayılması
arr5 = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2
broadcast_product = arr5 * scalar
print("\nBroadcasting product of arr5 and scalar:\n", broadcast_product)


Broadcasting sum of arr3 and arr4:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]

Broadcasting product of arr5 and scalar:
 [[ 2  4  6]
 [ 8 10 12]]


In [17]:
# Dizileri Birleştirme ve Bölme

# Birleştirme (Concatenate)
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[7, 8, 9], [10, 11, 12]])

concatenated_array = np.concatenate((arr3, arr4), axis=0)  # Satırları birleştirme
print("Concatenated array along rows:\n", concatenated_array)

concatenated_array = np.concatenate((arr3, arr4), axis=1)  # Sütunları birleştirme
print("\nConcatenated array along columns:\n", concatenated_array)

# Bölme (Split)
split_array = np.array_split(concatenated_array, 3, axis=1)  # Sütunları 3'e bölmek
print("\nSplit array along columns:\n", split_array)


Concatenated array along rows:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concatenated array along columns:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Split array along columns:
 [array([[1, 2],
       [4, 5]]), array([[ 3,  7],
       [ 6, 10]]), array([[ 8,  9],
       [11, 12]])]


In [18]:
# İleri Dizi İşlemleri

# Diziyi Yeniden Şekillendirme (Reshape)
arr5 = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = arr5.reshape(2, 3)  # 2x3 boyutlu diziye yeniden şekillendirme
print("Reshaped array:\n", reshaped_array)

# Transpoz Alma
transposed_array = arr2d.T  # Dizinin transpozunu al
print("\nTransposed array:\n", transposed_array)

# Diziyi Tek Boyuta Sıkıştırma (Flatten)
flattened_array = arr2d.flatten()  # Diziyi tek boyuta sıkıştır
print("\nFlattened array:", flattened_array)


Reshaped array:
 [[1 2 3]
 [4 5 6]]

Transposed array:
 [[0 3]
 [1 4]
 [2 5]]

Flattened array: [0 1 2 3 4 5]


In [23]:
import numpy as np


arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Dosya İşlemleri

# Diziyi Dosyaya Yazma
np.savetxt('array_data.txt', arr2d, delimiter=',')  # 2D diziyi belirtilen dosyaya virgülle ayrılmış olarak yazma

# Dosyadan Dizi Okuma
loaded_array = np.loadtxt('array_data.txt', delimiter=',')  # Belirtilen dosyadan dizi okuma
print("Loaded array from file:\n", loaded_array)

# Saving & Loading On Disk

# Diziyi diskte kaydetme
np.save('my_array.npy', arr2d)

# Birden fazla diziyi diskte kaydetme (zipleme)
np.savez('array.npz', arr1=arr2d, arr2=arr2d)

# Diziyi diskten yükleme
loaded_array = np.load('my_array.npy')

Loaded array from file:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [20]:
# Matris İşlemleri

# Matris Çarpımı
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix1, matrix2)
print("Matrix product:\n", matrix_product)

# Ters Matris Alma
matrix_inverse = np.linalg.inv(matrix1)
print("\nInverse of matrix1:\n", matrix_inverse)

# Determinant Bulma
matrix_determinant = np.linalg.det(matrix1)
print("\nDeterminant of matrix1:", matrix_determinant)


Matrix product:
 [[19 22]
 [43 50]]

Inverse of matrix1:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of matrix1: -2.0000000000000004


In [32]:
# DATA TYPES

# np.int64 veri tipi oluşturma
int_type = np.int64(5)
print("np.int64 example:", int_type)

# np.float32 veri tipi oluşturma
float_type = np.float32(3.14)
print("np.float32 example:", float_type)


# np.string_ veri tipi oluşturma
string_type = np.string_("world")
print("np.string_ example:", string_type)

# np.unicode_ veri tipi oluşturma
unicode_type = np.unicode_("hello")
print("np.unicode_ example:", unicode_type)


np.int64 example: 5
np.float32 example: 3.14
np.string_ example: b'world'
np.unicode_ example: hello


In [33]:
import numpy as np

# İki Dizi Arasında Karşılaştırma Yapma
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
comparison = arr1 == arr2
print("Comparison of arrays:", comparison)

# Karşılaştırma Operatörlerini Kullanarak Karşılaştırma Yapma
arr3 = np.array([1, 2, 3, 4, 5])
arr4 = np.array([3, 3, 3, 3, 3])
greater_than = arr3 > arr4
print("\nGreater than comparison:", greater_than)

# Dizi Elemanlarının Karşılaştırılması
arr5 = np.array([1, 2, 3, 4, 5])
greater_than_3 = arr5 > 3
print("\nComparison with scalar:", greater_than_3)

# Karşılaştırma Sonuçlarının Kullanımı
arr6 = np.array([1, 2, 3, 4, 5])
arr7 = np.array([0, 2, 4, 6, 8])
comparison_result = np.where(arr6 == arr7, "Equal", "Not Equal")
print("\nComparison result using np.where:", comparison_result)


Comparison of arrays: [False False  True False False]

Greater than comparison: [False False False  True  True]

Comparison with scalar: [False False False  True  True]

Comparison result using np.where: ['Not Equal' 'Equal' 'Not Equal' 'Not Equal' 'Not Equal']
